
# Site settings
title: "S.A.S.H.A"
email: team.automatediitb@gmail.com
description: "Smart Artificial System with Home Automation"
baseurl: "/sasha"
url: ""


# Team names, titles and social links
people:
- name: Omkar Ghugarkar
  pic: 11
  position: Team Leader
  social:
    - title: instagram
      url: https://www.instagram.com/mr.omkar.ghugarkar.007/
    - title: facebook
      url: https://www.facebook.com/omkarghugarkar7
    - title: linkedin
      url: https://www.linkedin.com/in/omkar-ghugarkar-94b897194/

- name: Bhuvan Aggarwal
  pic: 12
  position: Lead Coder
  social:
    - title: instagram
      url: https://www.instagram.com/bhuvan__18/
    - title: facebook
      url: https://www.facebook.com/bhuvan.aggarwal.16
    - title: linkedin
      url: https://www.linkedin.com/in/bhuvan-aggarwal-77b1b4191/

- name: Divyansh Natani
  pic: 13
  position: Asst. Coder and Lead Designer
  social:
    - title: instagram
      url: https://www.instagram.com/divyansh_natani/
    - title: facebook
      url: https://www.facebook.com/divyansh.natani.142
    - title: linkedin
      url: https://www.linkedin.com/in/divyansh-natani-b59389193/

      
- name: Akshat Zalte
  pic: 14
  position: Hardware Expert 
  social:
    - title: instagram
      url: https://www.instagram.com/akshat_zalte/
    - title: facebook
      url: https://www.facebook.com/akshat.zalte
    - title: linkedin
      url: https://www.linkedin.com/in/akshat-zalte-a78262196/

      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/akshat.zalte
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: ITSP, IIT Bombay
  - line: IIT Bombay, Powai, Mumbai 400 076,
  - line: Maharashtra, India

# Build settings
markdown: kramdown
permalink: pretty
